/**
 * js/config.js
 * ─────────────────────────────────────────────────────────────
 * Sasyam — Runtime configuration
 * NOTE: This file is auto-generated by scripts/generate-config.js
 *       at deploy time. Edit that script, not this file directly.
 * ─────────────────────────────────────────────────────────────
 */

const CONFIG = {
  /** FastAPI backend URL — change for production */
  BACKEND_URL: "http://localhost:8000",

  /** Gemini API key — injected at deploy time */
  GEMINI_API_KEY: "",

  /** Firebase project credentials — injected at deploy time */
  FIREBASE_CONFIG: {
    apiKey:            "",
    authDomain:        "",
    projectId:         "",
    storageBucket:     "",
    messagingSenderId: "",
    appId:             ""
  }
};

// Make available globally and as module export (works in both contexts)
if (typeof window !== "undefined") {
  window.CONFIG = CONFIG;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = CONFIG;
}
