#!/usr/bin/env node
/**
 * scripts/generate-config.js
 * ─────────────────────────────────────────────────────────────
 * Sasyam — Config generator for deploy-time injection
 *
 * Reads environment variables and writes js/config.js with
 * real values. Run this before deploying:
 *   node scripts/generate-config.js
 *
 * Required env vars:
 *   BACKEND_URL           — FastAPI backend URL
 *   GEMINI_API_KEY        — Google Gemini API key
 *   FIREBASE_API_KEY
 *   FIREBASE_AUTH_DOMAIN
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_STORAGE_BUCKET
 *   FIREBASE_MESSAGING_SENDER_ID
 *   FIREBASE_APP_ID
 * ─────────────────────────────────────────────────────────────
 */

const fs   = require("fs");
const path = require("path");

const env = process.env;

function require_env(key) {
  const val = env[key];
  if (!val) {
    console.warn(`[generate-config] WARNING: ${key} is not set. Using empty string.`);
    return "";
  }
  return val;
}

const config = {
  BACKEND_URL:    env.BACKEND_URL    || "http://localhost:8000",
  GEMINI_API_KEY: require_env("GEMINI_API_KEY"),
  FIREBASE_CONFIG: {
    apiKey:            require_env("FIREBASE_API_KEY"),
    authDomain:        require_env("FIREBASE_AUTH_DOMAIN"),
    projectId:         require_env("FIREBASE_PROJECT_ID"),
    storageBucket:     require_env("FIREBASE_STORAGE_BUCKET"),
    messagingSenderId: require_env("FIREBASE_MESSAGING_SENDER_ID"),
    appId:             require_env("FIREBASE_APP_ID")
  }
};

const outputPath = path.resolve(__dirname, "../js/config.js");

const content = `/**
 * js/config.js
 * NOTE: This file is auto-generated by scripts/generate-config.js at deploy time.
 * Do NOT edit manually — changes will be overwritten.
 * Generated: ${new Date().toISOString()}
 */

const CONFIG = ${JSON.stringify(config, null, 2)};

if (typeof window !== "undefined") {
  window.CONFIG = CONFIG;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = CONFIG;
}
`;

fs.writeFileSync(outputPath, content, "utf8");
console.log(`[generate-config] ✓ js/config.js written successfully.`);
console.log(`[generate-config]   BACKEND_URL       = ${config.BACKEND_URL}`);
console.log(`[generate-config]   FIREBASE_PROJECT  = ${config.FIREBASE_CONFIG.projectId || "(not set)"}`);
console.log(`[generate-config]   GEMINI_API_KEY    = ${config.GEMINI_API_KEY ? "✓ set" : "✗ not set"}`);
